gardener/gardenctl

cmd/miscellaneous.go, cmd/show.go
The credentials for prometheus, alertmanager and grafana are now stored in the `monitoring-ingress-credentials` secret inside the shoot's controlplane namespace on the seed cluster.
This PR makes it so that the secrets are retrieved from the correct place.
As getCredentials() is not used anywhere else in the code it was completely replaced by getMonitoringCredentials().
Fixes issue #46
=> Fixes credentials for monitoring tools

.ci/pipeline_definitions, Dockerfile
> We have just released Go 1.11.5 and Go 1.10.8 to address a recently reported security issue. We recommend that all users update to one of these releases (if you’re not sure which, choose Go 1.11.5).
>
> This DoS vulnerability in the crypto/elliptic implementations of the P-521 and P-384 elliptic curves may let an attacker craft inputs that consume excessive amounts of CPU.
>
> These inputs might be delivered via TLS handshakes, X.509 certificates, JWT tokens, ECDH shares or ECDSA signatures. In some cases, if an ECDH private key is reused more than once, the attack can also lead to key recovery.
>
> The issue is CVE-2019-6486.
n/a
n/a
```improvement operator …
```
=> Upgrade golang version to 1.11.5

README.md, cmd/logs.go
With this PR the `gardenctl logs` command will be able to take the logs both from `kubectl` and `elasticsearch`. There are several new flags we can use in the command:
`--elasticsearch`(For getting the logs from elasticsearch)
`--tail=X`(Getting the last X logs)
`--since=Xs/m/h`(Getting the logs from last X seconds/minutes/hours)
`--since-time=RFC3339-format`(Getting the logs from after the specified time)
CC: @ialidzhikov @vlvasilev @vlerenc @vpnachev @plkokanov
=> update gardenctl logs command

cmd/root.go
Follow up on #57
The `kubectl` defines `__custom_func` as well as the `gardenctl`. As result, the latest sourced completion file overwrite the already defined `__custom_func` func.
See [the example here](https://github.com/spf13/cobra/blob/master/bash_completions.md#creating-your-own-custom-functions)
=> Prevent function name collision in completion script

cmd/show.go
Modify `show` to be able to show the seed kibana instance when the target is a seed.
Fixes #
```improvement operator
`gardenctl show kibana` now also shows the appropriate kibana instance when the target is a seed.
```
=> Modify show to handle seed kibana

.ci/pipeline_definitions, Dockerfile
https://golang.org/doc/go1.12
Fixes #
```improvement operator
The golang version has been upgraded to `v1.12.0`.
```
=> Update golang to 1.12.0

.ci/pipeline_definitions, .github/pull_request_template.md
- Adds PR template
- Enables draft releases
- Posts release notes to internal slack channel
Fixes #
```improvement operator
NONE
```
=> Add PR template, enable draft releases, post to slack

cmd/shell.go
`gardenctl shell <node>` fails with
```
pod/rootpod-<user> created
pod not found: pods "rootpod-<user>" not found
pod not found: pods "rootpod-<user>" not found
pod not found: pods "rootpod-<user>" not found
[...]
```
when the second target in the target stack is seed.
Work in progress, unit tests to be added.
Fixes #
```improvement operator
`gardenctl shell <node>` now properly handles cases when the second target in the target stack is seed.
```
=> Improve shell command

cmd/aliyun.go, cmd/operate.go, cmd/root.go
Integrate aliyun infrastructure cli with gardenctl.
Fixes #68 
cc Jerry, Minchao
```improvement operator
'gardenctl aliyun <args>' is now available on alicloud clusters.
```
=> integrate aliyun cli with gardenctl

Gopkg.lock, cmd/cmd_suite_test.go, cmd/drop.go, cmd/logs.go, cmd/miscellaneous.go, cmd/miscellaneous_test.go, cmd/mocks.go, cmd/shell.go, cmd/shell_test.go, cmd/show.go, cmd/target.go, cmd/target_provider.go, cmd/types.go, cmd/utils_test.go, cmd/version.go, vendor/k8s.io/apimachinery/pkg/util/wait/doc.go, vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
- Introduce `TargetKind` type to limit usage of inline strings for target kind.
- Use client-go in shell command wherever possible.
Fixes #
```improvement operator
NONE
```
=> Add TargetKind type

cmd/drop_test.go, cmd/shell.go, cmd/shell_test.go
The value of kubernetes.io/hostname may be the same as the Node name in some environments and a different value in other environments ([source](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#interlude-built-in-node-labels)).
The PR removes the `strings.Contains(host["kubernetes.io/hostname"], name)` check which was preventing shell cmd to work with JeOS nodes.
Ref #83 
```improvement operator
NONE
```
=> Improve nodeSelector in shell cmd

cmd/drop_test.go, cmd/ls.go, cmd/ls_test.go, cmd/root.go, cmd/target.go, cmd/target_test.go
List suggestions when `gardenctl target garden` is used.
Fixes #86
```improvement operator
NONE
```
=> List suggestions when gardenctl target garden is used

.ci/build, .ci/test, Dockerfile, Makefile
For cmd/go the default behaviour in go modules is to look up the proper modules through the network. `-mod=vendor` prevents that and forces the use of `vendor/`.
Ref golang/go#27227
Fixes #
```improvement operator
NONE
```
=> Use -mod=vendor

.github/pull_request_template.md
This PR adds the `developer` target group to the pull request template
Fixes #
`developer` target group was introduced with https://github.com/gardener/cc-utils/pull/303
```improvement operator
NONE
```
=> PR-Template: add developer target group

cmd/ssh.go, cmd/ssh_for_alicloud.go
Enable using gardenctl to ssh onto alicloud clusters.
-  `gardenctl ssh` will list all the nodes of the cluster.
- `gardenctl ssh <nodeIP>` will create a bastion host, a corresponding security group and allocates a public ip for it. Then it will prints out all the commands to:
1. Ssh onto the target node.
2. Hibernate the bastion host.
3. Cleanup the bastion setting.
- `gardenctl ssh clean` will clean up the security group and bastion host instance of a alicloud node.
Fixes #71 
```improvement operator
Enable gardenctl ssh access to Alicloud clusters.
```
=> Enable gardenctl ssh to Alicloud clusters

pkg/cmd/ssh.go, pkg/cmd/ssh_for_alicloud.go
Short term fix of SSH command, where the user will be asked to enter the `user` which will be used for ssh
https://github.com/gardener/gardenctl/issues/108
@ialidzhikov @DockToFuture 
-->
```improvement operator
Add placeholders to the `SSH` command for user which will be used for connecting to the node.
```
=> Short term fix for SSH command

Dockerfile, README.md, pkg/cmd/completion.go
Output the completion script to the std out.
Add experimental support for zsh.
Fixes #102
/cc @vasu1124 
```action user
`gardenctl completion` now accepts shell subcommand, `bash` or `zsh`.
```
```action user
`gardenctl completion <shell>` no longer print the completion script to the file `gardenctl_completion.sh` file, but on the standard output.
```
```improvement user
`gardenctl completion` has an experimental support for `zsh` shell.
```
=> Improve completion

pkg/cmd/download.go, pkg/cmd/get.go, pkg/cmd/logs.go, pkg/cmd/operate.go, pkg/cmd/root.go, pkg/cmd/show.go, pkg/cmd/ssh_for_alicloud.go, pkg/cmd/target.go, pkg/cmd/var.go
Currently the `gardenctl target seed/shoot` commands navigates to `/cache/seeds/`. This may cause a problem which I will describe bellow:
1) Let's open a terminal and target some garden cluster and after that some seed cluster , for example `aws`.
This will create a file in .garden/cache/seeds/aws/kubeconfig.yaml and will print it.
2) export KUBECONFIG=.garden/cache/seeds/aws/kubeconfig.yaml
3) Open another terminal where we will target again seed called `aws` but from another garden cluster. This will override the file, which points the Kubeconfig from the first terminal.
We can just add the garden cluster's name to the Kubeconfig's path
Fixes #
@vpnachev @DockToFuture …
=> Improve target command

pkg/cmd/download.go, pkg/cmd/get.go, pkg/cmd/operate.go, pkg/cmd/register.go, pkg/cmd/ssh.go, pkg/cmd/ssh_for_alicloud.go, pkg/cmd/target.go, pkg/cmd/unregister.go
Replace hard coded paths with filepath.Join(). 
In this way, the paths will be relevant to Windows systems too.
Fixes #
@ialidzhikov @DockToFuture 
```improvement operator
NONE
```
=> Replace hard coded strings with filepath.Join

pkg/cmd/info.go, pkg/cmd/info_test.go, pkg/cmd/root.go
Fix panic in info cmd occurring when Shoot `.spec.cloud.<provider>.seed` is `nil`. These entries are now shown as `unscheduled` in the output.
Fixes #
```improvement operator
NONE
```
=> Fix panic in info cmd when Shoot is unscheduled

go.mod, pkg/cmd/ssh.go, pkg/cmd/ssh_alicloud.go, pkg/cmd/ssh_aws.go, pkg/cmd/ssh_azure.go, pkg/cmd/ssh_gcp.go
- Automates ssh cmd for aws, azure and gcp.
- Splits ssh cmd into separate files to make it more readable
- Read ssh config from garden cluster
- Print warning when entering untrusted zone
Fixes: 
- https://github.com/gardener/gardenctl/issues/73
- https://github.com/gardener/gardenctl/issues/123
- https://github.com/gardener/gardenctl/issues/126
```improvement operator
- Improved ssh cmd for aws, azure and gcp
```
=> Automate ssh cmd for aws, azure and gcp

go.sum, pkg/cmd/miscellaneous.go, pkg/cmd/utils.go
Referenced Kubeconfigs may now only contain the following keys as authentication info: `client-certificate-data`, `client-key-data`, `token`, `username`, or `password`.
Fixes #136
```improvement operator
For kubeconfig authentication only the following keys: `client-certificate-data`, `client-key-data`, `token`, `username`, or `password` are allowed.
```
=> Restrict kubeconfig authentication info to prevent dark side of kubeconfig hack

README.md, pkg/cmd/miscellaneous.go, pkg/cmd/register.go, pkg/cmd/types.go, pkg/cmd/unregister.go
E-mail can now also be read from config for register/unregister cmd.
Precedence order, starting with highest precedence:
1. Specified e-mail as argument
2. Specified e-mail in config
3. Read from github URL
Sample configuration:
``` yaml
email: john.doe@example.com
githubURL: https://github.location.company.corp
gardenClusters:
- name: dev
```
Fixes #124 
```improvement operator
E-mail can now also be read from config for register/unregister cmd.
```
=> Read email from config for register/unregister cmd

pkg/cmd/ssh_aws.go, pkg/cmd/ssh_azure.go, pkg/cmd/ssh_gcp.go
Tag all infrastructure resources created by gardenctl.
Currently implementation supports tagging for aws, azure and gcp.
Fixes #141 
Currently all created resources are tagged but not the updated ones.
```improvement operator
Tag all infrastructure resources created by gardenctl for aws, azure and gcp.
```
=> Tag all infra resources created by gardenctl

pkg/cmd/logs.go
Add support for `cluster-autoscaler` for `gardenctl logs` command
https://github.com/gardener/gardenctl/issues/69
@DockToFuture @ialidzhikov 
```improvement operator
NONE
```
=> Cluster Autoscaler Support

pkg/cmd/ssh_alicloud.go
Fix cleanup tips of ssh to alicloud Shoot. Change from `gardenctl ssh clean` to `gardenctl ssh cleanup`.
Fixes #
Hi, I just noticed that using gardener user to ssh to Alicloud bastion host & Shoot node has already been implemented. Thanks for the effort! I find this small output issue that you missed when you updated the feature.
```improvement operator
```
=> fix minor issue for cleanup tips of alicloud bastion host

pkg/cmd/show.go
`gardenctl show` command supports now `cluster-autoscaler`
https://github.com/gardener/gardenctl/issues/69
@ialidzhikov @DockToFuture 
```improvement operator
NONE
```
=> Show command for cluster-autoscaler

pkg/cmd/ssh_alicloud.go, pkg/cmd/ssh_aws.go, pkg/cmd/ssh_azure.go, pkg/cmd/ssh_gcp.go
Currently if we have node which can not join the cluster, the MCM will wait 20 min and after that will replace it with new one. During this time if we are `ssh` on this node, the `cmd.Run()` will crash with error and `checkError(err)` will terminate the function before the created resources are being deleted (We do not want this to happen).
So this PR fixes this scenario. 
Fixes #
@DockToFuture 
```improvement operator
NONE
```
=> Improve SSH check

pkg/cmd/target.go
When targeting a shoot and kubeconfig is not available, use empty one to allow limited set of cmds on shoot.
Fixes #132 
```improvement operator
none
```
=> Target shoot without an available kubeconfig

pkg/cmd/register.go
gardener/gardener#1601 renames `garden.sapcloud.io:system:administrators` to `gardener.cloud:system:administrators`.
Fixes #
```improvement operator
NONE
```
=> Update administrators ClusterRoleBinding name

pkg/cmd/download.go, pkg/cmd/root.go, pkg/cmd/target.go
Target flags are added for garden, seed, project and shoot.
Fixes  #143 
```improvement operator
Target flags are added for garden, seed, project and shoot.
```
=> add target flags

README.md, pkg/cmd/root.go, pkg/cmd/var.go
Sessions are added to `gardenctl`. This allows to operate on multiple clusters at the same time in different terminal sessions which was not possible before. The session ID can be set via the `GARDEN_SESSION_ID` environment variable.
```improvement operator
Sessions are added to `gardenctl`. This allows to operate on multiple clusters at the same time in different terminal sessions which was not possible before. The session ID can be set via the `GARDEN_SESSION_ID` environment variable.
```
=> Add sessions to gardenctl

pkg/cmd/ssh.go
this is for https://github.com/gardener/gardenctl/issues/161
currently when using `gardenctl ssh node_name` the key is downloaded in current dir.
Per suggestion from https://github.com/gardener/gardenctl/issues/161#issuecomment-583126960 moving key to shoot cache dir
=> issue-161, move key from current dir to shoot cache

go.mod, go.sum, pkg/cmd/version.go, vendor/github.com/mcuadros/go-version/.gitignore, vendor/github.com/mcuadros/go-version/.travis.yml, vendor/github.com/mcuadros/go-version/LICENSE, vendor/github.com/mcuadros/go-version/README.md, vendor/github.com/mcuadros/go-version/compare.go, vendor/github.com/mcuadros/go-version/constraint.go, vendor/github.com/mcuadros/go-version/doc.go, vendor/github.com/mcuadros/go-version/group.go, vendor/github.com/mcuadros/go-version/normalize.go, vendor/github.com/mcuadros/go-version/sort.go, vendor/github.com/mcuadros/go-version/stability.go, vendor/modules.txt
This PR enables notification to end user when a new version of `gardenctl` is available while running `gardenctl version` command
Fixes #
https://github.com/gardener/gardenctl/issues/160
1) i added "new version notification" to command `gardenctl version` as the value of `VERSION` is injected in `gardenctl version` command only
2) to compare version numbers (in gardenctl it's e.g. `v0.15.0` or `v0.16.0`) i use one library `github.com/mcuadros/go-version`
```improvement user
If a newer version of gardenctl is available, command "gardenctl version" will show notification including where and how to upgrade.
```
=> issue 160 - add upgrade notification when new version available

pkg/cmd/root.go, pkg/cmd/target.go, pkg/cmd/target_test.go
This PR enables `gardenctl target` command to switch to one namespace after target garden/seed/project/shoot
`gardenctl target namespace kube-system`
`gardenctl target -n kube-system`
and then you can get pods in `kube-system` in `gardenctl k get pods`
Fixes #
https://github.com/gardener/gardenctl/issues/165
* Personally i don't think my implementation of this issue is nice, as 
** namespace is kind of concept in k8s native, meanwhile `target` is native concept for gardener, this command just for make life easier compared with you need to explicitly write the name of namespace each time like `gardenctl k get pods -- -n shoot_techinical_id`
** in `gardenctl target` it deals target …
=> add support for gardenctl target namespace xxx or gardenctl target -m xxx

pkg/cmd/drop.go, pkg/cmd/ls.go, pkg/cmd/ls_test.go, pkg/cmd/target.go, pkg/cmd/types.go
This PR makes namespace to be one kind of target, just like garden/seed/project/shoot
Fixes # https://github.com/gardener/gardenctl/issues/169
* `gardenctl ls namespace` is supported
* i've tested in following scenario/combination
```
gardenctl target -g canary-virtual -s gcp-eu2 -p everest -t ev-1373-b -n kube-system
gardenctl target -g canary-virtual -s gcp-eu2 -p everest -n kube-system
gardenctl target -g canary-virtual -s gcp-eu2 -n kube-system
gardenctl target -g canary-virtual -n kube-system
gardenctl target -s gcp-eu2 -p everest -t ev-1373-b -n kube-system
gardenctl target -s gcp-eu2 -t ev-1373-b -n kube-system
gardenctl target -s gcp-eu2 -n kube-system
gardenctl target -p …
```
=> refactor namespace to kind of target

pkg/cmd/ls.go
Fix panic error when running `gardenctl ls issues`
Fixes https://github.com/gardener/gardenctl/issues/176
```improvement user
An error which occurs running `gardenctl ls issues` is now fixed.
```
=> fix ls issue panic

go.mod, go.sum, pkg/cmd/root.go, pkg/cmd/update-check.go, pkg/cmd/version.go
Move check for newer version to dedicated command
It is very annoying `gardenctl version` to depend on network connectivity, thus moving the this check to dedicated command.
Fixes #
```noteworthy user
The check for newer version is now moved to dedicated sub-command, e.g. `gardenctl update-check`.
```
=> Move check for newer version to dedicated command

pkg/cmd/root.go, pkg/cmd/target.go, pkg/cmd/target_test.go
add support for gardenctl target server / gardenctl target -r
the server should be in format "https://servername:443" or "https://ipaddress:443"
Fixes https://github.com/gardener/gardenctl/issues/164
`gardenctl target server https://hostname:443`
`gardenctl target -r https://ipaddress:443 -s xxx -n xxx`
```improvement operator
Added support for `gardenctl target server <uri>` / `gardenctl target -r <uri>` / `gardenctl target --server <uri>` to target a garden without knowing the garden name which can be different on each local installation
- The uri may be an ip or hostname
```
=> add support for gardenctl target server / gardenctl target -r

pkg/cmd/target.go
Patching the `kubeConfig` path in case it contains the `~` (tilde) sign should be done before checking if the file exists, otherwise the check fails
Fixes #
```improvement operator
`target server` now also works when the `kubeConfig` path of the garden configuration contains the `~` (tilde) sign
```
=> [target server] Fix home directory issue

pkg/cmd/get.go, pkg/cmd/miscellaneous.go, pkg/cmd/register.go, pkg/cmd/target.go, pkg/cmd/unregister.go, pkg/cmd/utils.go
in g/gardenctl repo there are many 
```
if strings.Contains(pathToKubeconfig, "~") {
pathToKubeconfig = filepath.Clean(filepath.Join(HomeDir(), strings.Replace(pathToKubeconfig, "~", "", 1)))
}
```
refactor them to be one function and make code clean
Fixes https://github.com/gardener/gardenctl/issues/181
```improvement operator
NONE
```
=> issue-181 refactor kubeconfig path read function

README.md, pkg/cmd/logs.go
add: `gardenctl logs` readme 
fix: `gardenctl logs tf infra` result output null 
add: `gardenctl logs tf infra shoot-name` result output display only from shoot cluster instead of all shoot clusters 
Fixes https://github.com/gardener/gardenctl/issues/183
```improvement operator
gardenctl logs tf infra output null fix and logs function README update
```
=> gardenctl logs tf fix

pkg/cmd/target.go, pkg/cmd/target_test.go, pkg/cmd/types.go
Enable `gardenctl target dashboardUrl dashboard_url` or `gardenctl target -u dashboard_url` for directly targeting garden and shoot
This requires your (virtual) garden config to have `dashboardUrl` field set.
E.g.
```yaml
gardenClusters:
- kubeConfig: /path/to/kubeconfig.yaml
name: foo
dashboardUrl: https://dashboard.foo.example.com
```
Fixes https://github.com/gardener/gardenctl/issues/188
the url could be in following two formats:
- https://<url-to-dashboard>/namespace/garden-project/shoots/my-shoot/
- https://<url-to-dashboard>/namespace/garden-project/shoots/my-shoot
```improvement operator
Enable `gardenctl target dashboardUrl <dashboard_url>` or `gardenctl …
```
=> add support for target url or target -u with dashboard url

pkg/cmd/aliyun.go, pkg/cmd/aws.go, pkg/cmd/az.go, pkg/cmd/gcloud.go, pkg/cmd/get.go, pkg/cmd/openstack.go, pkg/cmd/ssh.go, pkg/cmd/utils.go
Sometimes ago we only have `garden` / `seed` / `project` / `shoot` in kinds of target, so when len(target.Stack())>=3, there must be one shoot targeted.
Now there's one new kind of `namespace` in kinds of target, so when len(target.Stack())>=3 , shoot might not be targeted, which might causing some command fail (e.g. `gardenctl az` related commands)
Fixes https://github.com/gardener/gardenctl/issues/196
This error was found in executing `gardenctl az` but also found across the whole project, so refactor them all together
```improvement user
Fixes gardenctl related error in certain kind of scenario when gardenctl not targeting shoot
```
=> add shoot target check when target.Stack() length >= 3

README.md
added homebrew setup instructions
```improvement user
gardenctl can be now conviniently installed via homebrew tap with
"brew install gardener/tap/gardenctl"
```
=> added homebrew setup instructions

pkg/cmd/ssh.go, pkg/cmd/ssh_alicloud.go
Previously gardenctl fixed the problem that when doing ssh, an id_rsa.pub key will be created in current folder. However, it was not applied to alicloud provider.
This PR fixes alicloud ssh command and makes it aligned with other providers'.
Fixes #
```improvement operator
Fix the issue that breaks ssh command for provider alicloud.
```
=> fix alicloud ssh

pkg/cmd/miscellaneous.go, pkg/cmd/ssh_aws.go, pkg/cmd/ssh_azure.go, pkg/cmd/ssh_gcp.go
gardenctl should not rely on installed jq
Fixes #74 
```improvement operator
Remove jq tool dependency
```
=> Remove jq tool dependency

pkg/cmd/operate.go
gardenctl gets wrong shoot creds for shoots w/ same name across diff projects
Fixes #147 
```improvement operator
validate shoot project matches shoot namespace w/ same name across diff projects
```
=> validate shoot project matches shoot namespace

pkg/cmd/kubectx.go, pkg/cmd/root.go
Add kubectx support for gardenctl
Fixes https://github.com/gardener/gardenctl/issues/211
```improvement operator
add kubectx support for gardenctl
```
=> Add kubectx support for gardenctl

pkg/cmd/ssh_aws.go
AWS IAM Instance Profiles are not needed for bastions as they should be used only to jump to the broken instances.
See AWS [EC2 RunInstances API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html).
Fixes # n/a
Related issue https://github.com/gardener/gardener-extension-provider-aws/issues/4
```improvement operator
AWS Bastion nodes no longer have any instance profiles associated with them.
```
=> Remove AWS instance profile from bastion nodes

.ci/pipeline_definitions
This PR updates the pipeline definition with automatic publishing of a docker image based on the already created dockerfile.
Fixes #210 
@petersutter 
As discussed in #210 I oriented on the supplied examples in the issue. Let me know in case I should go for any changes👍 
```improvement operator
```
Best Regards & Take Care
Robert
=> Add pipeline job for automatic creation and publish of gardenctl docker image

pkg/cmd/utils.go
In gardenctl there's validation against kubeconfig which doesn't allow kubeconfig contains `exec` or `auth provider` to prevent malicious executable code. Now with OIDC enabled, kubeconfig contains exec part, so i would like to propose this PR to discuss whether we can remove this check in gardenctl 
Fixes https://github.com/gardener/gardenctl/issues/217 and https://github.com/gardener/gardenctl/issues/175
/CC @dansible @ThormaehlenFred @DockToFuture @ialidzhikov @vpnachev @donistz 
Basically this PR enables gardenctl to utilize oidc enabled kubeconfig, i did some basic testing like `gardenctl target garden/seed/shoot` and then do some kubectl operation like `gardenctl k get pods …
=> remove exec and auth provider check to utilize kubeconfig with oidc enabled

pkg/cmd/miscellaneous.go, pkg/cmd/ssh.go, pkg/cmd/ssh_alicloud.go, pkg/cmd/ssh_aws.go, pkg/cmd/ssh_azure.go, pkg/cmd/ssh_gcp.go
What this PR does / why we need it:
fetch user Public IP and restrict the source IP range
create ssh rules in security group base on user public IP when use gardenctl ssh instead of 0.0.0.0/0
Which issue(s) this PR fixes:
Fixes #222
Special notes for your reviewer:
Release note:
restrict the source IP range when use gardenctl ssh
the previous PR closed by the accident
=> restrict Public IP when use ssh access cloud

README.md
in README.md, there's only guide for how to enable command line auto completion of `bash`, actually different command should be run to enable auto completion when you are running `bash` or `zsh`
Fixes https://github.com/gardener/gardenctl/issues/227
```improvement operator
add documentation for how to enable cli auto completion in zsh
```
=> add documentation for how to enable source completion in zsh

CODEOWNERS
Use gardenctl-maintainers group for CODEOWNERS
=> use gardenctl-maintainers group

.github/workflows/update-gardenctl.yml
Add a github action to update gardenctl  homebrew-tap
**Note to reviewer** 
We should create a secret token able to do workflow updates
```improvement operator
An update to homebrew-tap is now automatically triggered. 
```
=> Add github action to update gardenctl homebrew-tap
